### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pollat** [cdigruttola/barcodegenerator#1]
I tryed to install this plugin on prestashop 1.7.8.10 version, but I get installation error.

**Comment by cdigruttola** [comment]
What kind of error?

**Comment by pollat** [comment]
LUCA NAPPINI ha condiviso il seguente file con te:

scrnli_9_4_2024_14-33-51.png

Visualizza file https://share.mail.libero.it/ajax/share/03eea240096e0242376a46d96e0246aca2a7f8bd7e2a4d06/2/m8/fRE1RRlM6Ly9kcml2ZW1haWwtZGVmYXVsdC1hY2NvdW50LzQ5MDM2OD0yMzk5NjMwNTM/aZHJpdmVtYWlsLnJlY2lwaWVudA~cmVwbHkrQUNJWVkyTTJaVkhPUlJSWEJQWVJXUFdFRURZN1RFVkJOSEhJS0Y3NU40QHJlcGx5LmdpdGh1Yi5jb20.ZHJpdmVtYWlsLmZvbGRlcmlk~NDkwMzY4Izk5NjMwNTM

Il collegamento scadrà il 16 aprile 2024


---------------------------------------------

Utilizza il link sopra per scaricare i file. Si aprirà una nuova pagina dalla quale potrai scegliere quali file scaricare.

To download all desired files click on the link above. You will be taken to a new page that allows you to pick the files you want to download.


---------------------------------------------



see image attached....

**Comment by cdigruttola** [comment]
Hi, 
you have to create the zip to upload the module. The zip downloaded via https://github.com/cdigruttola/barcodegenerator/archive/refs/heads/master.zip is not valid. 
the zip anche folder inside must have named barcodegenerator.zip e the folder must be barcodegenerator

**Comment by pollat** [comment]
I file che ***@***.*** ha condiviso con te sono scaduti

* scrnli_9_4_2024_14-33-51.png
